development:
 adapter: postgresql
 encoding: unicode
 database: ticket_tracker_dev
 host: localhost
 pool: 5
 username: jamesnewman
 password: password

test:
 adapter: postgresql
 encoding: unicode
 database: ticket_tracker_testing
 host: localhost
 pool: 5
 username: jamesnewman
 password: password

production:
 adapter: postgresql
 encoding: unicode
 database: ticket_tracker
 #host: localhost
 pool: 5
 username: jamesnewman
 password: password